#!/bin/sh
#
# ci_pre_xcodebuild.sh
# Runs automatically in Xcode Cloud before every xcodebuild invocation.
#
# Generates Config/Secrets.xcconfig from workflow environment variables so
# the build can access Firebase keys without committing them to the repository.
#
# Required variables — set in App Store Connect → Xcode Cloud → Workflow →
# Environment → Environment Variables (mark each as Secret):
#
#   FIREBASE_API_KEY
#   FIREBASE_GCM_SENDER_ID
#   FIREBASE_PROJECT_ID
#   FIREBASE_STORAGE_BUCKET
#   FIREBASE_GOOGLE_APP_ID
#
# If any variable is absent the corresponding xcconfig key is left empty and
# Firebase will not be configured at runtime (configureFirebase() guards this).

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_FILE="$REPO_ROOT/Config/Secrets.xcconfig"

echo "ci_pre_xcodebuild: writing $SECRETS_FILE"

cat > "$SECRETS_FILE" <<EOF
// Auto-generated by ci_scripts/ci_pre_xcodebuild.sh — do not commit.
FIREBASE_API_KEY = ${FIREBASE_API_KEY:-}
FIREBASE_GCM_SENDER_ID = ${FIREBASE_GCM_SENDER_ID:-}
FIREBASE_PROJECT_ID = ${FIREBASE_PROJECT_ID:-}
FIREBASE_STORAGE_BUCKET = ${FIREBASE_STORAGE_BUCKET:-}
FIREBASE_GOOGLE_APP_ID = ${FIREBASE_GOOGLE_APP_ID:-}
GOOGLE_APP_ID = \$(FIREBASE_GOOGLE_APP_ID)
EOF

echo "ci_pre_xcodebuild: done."
